name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Code_Formating
  pull_request:
    branches:
      - main
      - Code_Formating

jobs:
  configure-dependencies:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.10.14]
    steps:
    - uses: actions/setup-python@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jsonschema Flask requests

  code-preparation:
    needs: configure-dependencies
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-python@v4
    - name: Set executable permissions for scripts
      run: chmod +x ./scripts/*.sh
    - name: Install code formatting and quality tools
      run: |
        pip install black
        pip install pylint flake8
    - name: Code formatting with Black
      run: ./scripts/format_code_black.sh
    - name: Code quality checks
      run: |
        ./scripts/check_quality_pylint.sh
        ./scripts/check_quality_flake8.sh

  # tests:
  #   needs: code-preparation
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install test dependencies
  #     run: |
  #       pip install pytest flask jsonschema pydantic coverage
  #   - name: Run tests
  #     run: ./scripts/run_tests.sh
  #   - name: Test coverage
  #     run: ./scripts/check_test_coverage.sh

  # other-tests:
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install other test tools
  #     run: |
  #       pip install radon bandit
  #   - name: Other quality checks
  #     run: |
  #       ./scripts/check_quality_radon.sh
  #       ./scripts/check_quality_bandit.sh
