name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Code_Formating
      - Code_Testing
  pull_request:
    branches:
      - main
      - Code_Formating

jobs:
  configure-dependencies:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.10.14]
    steps:
    - uses: actions/checkout@v3  # Añadir esto para hacer checkout del código
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Actualizar pip

  code-formatting:
    needs: configure-dependencies
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set executable permissions for scripts
      run: chmod +x ./scripts/format_code_black.sh ./scripts/check_quality_pylint.sh ./scripts/check_quality_flake8.sh
    - name: Install code formatting and quality tools
      run: |
        pip install black
        pip install pylint 
        pip install flake8
    - name: Code formatting with Black
      run: ./scripts/format_code_black.sh
    - name: Code quality checks
      run: |
        ./scripts/check_quality_pylint.sh
        ./scripts/check_quality_flake8.sh

  tests:
    needs: code-formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set executable permissions for scripts
      run: chmod +x ./scripts/run_tests.sh
    - name: Install test dependencies
      run: |
        pip install pytest flask
        pip install -r requirements.txt
    - name: Export API Key to Environment
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
    - name: Run tests
      run: |
        ./scripts/run_tests.sh

  other-tests:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set executable permissions for scripts
      run: chmod +x ./scripts/check_quality_radon.sh ./scripts/check_quality_bandit.sh
    - name: Install test dependencies
      run: |
        pip install pytest flask
        pip install -r requirements.txt
    - name: Install other test tools
      run: |
        pip install radon bandit
    - name: Run complexity
      run: |
        ./scripts/check_quality_radon.sh
    - name: Run security checks
      run: |
        ./scripts/check_quality_bandit.sh

  frontend-code-formatting-and-tests:
    needs: code-formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: |
        npm install
        npm install --save-dev prettier
        npm install --save-dev eslint eslint-config-react
        npm install --save-dev stylelint stylelint-config-standard

    - name: Run formating and quality checks
      run: |
        ./scripts/check_format_frontend.sh
        ./scripts/check_quality_frontend.sh

    # - name: Run frontend tests
    #   run: npm test 